version: '3.3'
services:


  odoo:
    image: odoo:12.0
    ports:
      - "8050:8069"
    volumes:
      - /opt/odoo/odoo-docker/docker-compose-odoo-12-0/etc:/etc/odoo
      - /opt/odoo/addons/odoo12:/mnt/extra-addons
    networks:
      - default
      - db_network
    external_links:
      - docker-compose-odoo-11-0_postgres_1:db


networks:
    db_network:
        external:
            name: docker-compose-odoo-11-0_default
